# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8092
  servlet:
    # 应用的访问路径
    context-path: /
    multipart:
      #设置文件上传最大大小为20MB
      max-file-size: 20MB
      #设置请求最大大小为20MB
      max-request-size: 20MB
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
    #设置内置Tomcat请求大小为20MB
    max-http-form-post-size: 20MB

fast:
  apply-name: manage

attach:
  profile-win: D:/fast/manage
  profile-linux: /doc/fast/manage


spring:
  config:
    import:
      # 能够正常加载只是识别不到
      - classpath:/service-common-application.yml
  # 开发环境配置
  redis:
    host: fast.com
    port: 6377
    password: 27ac1ca76c1037366c17852e01a24bb7432ef4c
    database: 0
    timeout: 10000
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0



  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      #      master:
      url: jdbc:mysql://fast.com:3336/fast?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: 27ac1ca76c1037366c17852e01a24bb7432ef4c
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置连接超时时间
      connectTimeout: 30000
      # 配置网络超时时间
      socketTimeout: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: manage
        login-password: 123456
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
      additional-paths: src/main/java #重启目录
      exclude: templates/** #classpath目录下的templates文件夹内容修改不重启



############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Fast-Token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: 3600
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  # 本框架已经使用 jwt-simple 模式，is-share=false 恒等于 false。
  # is-share=true 的意思是每次登录都产生一样的 token，这种策略和 [ 为每个 token 单独设定 setExtra 数据 ] 不兼容的， 为保证正确设定 Extra 数据，当使用 jwt-simple 模式后，is-share 配置项 恒等于 false。
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # 不答应启动LOGO
  isPrint: false
  # jwt秘钥
  jwt-secret-key: aaaaaaaaaaasdadasda

# 日志配置
logging:
  level:
    com.fast.manage.dao: info
    com.fast.common.dao: info
    org.springframework: info
  file:
    name: manage.log