# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8092
  servlet:
    # 应用的访问路径
    context-path: /
    multipart:
      #设置文件上传最大大小为20MB
      max-file-size: 20MB
      #设置请求最大大小为20MB
      max-request-size: 20MB
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
    #设置内置Tomcat请求大小为20MB
    max-http-form-post-size: 20MB

fast:
  apply-name: manage

attach:
  profile-win: D:/fast/manage
  profile-linux: /doc/fast/manage


spring:
  config:
    import:
      # 能够正常加载只是识别不到
      - classpath:/service-common-application.yml
  # 开发环境配置
  redis:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1
    host: fast.com
    port: 6379
    password: 123456
    database: 0
    timeout: 10000


  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      #      master:
      url: jdbc:mysql://fast.com:3336/fast?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: 27ac1ca76c1037366c17852e01a24bb7432ef4c

  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
      additional-paths: src/main/java #重启目录
      exclude: templates/** #classpath目录下的templates文件夹内容修改不重启



############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Fast-Token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # 不答应启动LOGO
  isPrint: false
  # jwt秘钥
  jwt-secret-key: aaaaaaaaaaasdadasda


