
-- 初始化菜单
INSERT INTO sys_menu(`name`, `parent_id`, `order_num`, `url`, `target`, `menu_type`, `visible`, `is_refresh`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `version`, `del_flag`)VALUES ('系统参数配置', 0, 0, 'common/config/index', 'menuItem', 'C', '1', '0', 'common.config.page', '#', '1', now(), '', now(), '', 1, '0');

INSERT INTO sys_menu(`name`, `parent_id`, `order_num`, `url`, `target`, `menu_type`, `visible`, `is_refresh`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `version`, `del_flag`)VALUES ('系统参数配置查看', (SELECT max(id) from (SELECT * from sys_menu ) as temp where `name` = '系统参数配置'), 6, '', 'menuItem', 'F', '1', '0', 'common.config.page', '#', '1', now(), '', now(), '', 1, '0');
INSERT INTO sys_menu(`name`, `parent_id`, `order_num`, `url`, `target`, `menu_type`, `visible`, `is_refresh`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `version`, `del_flag`)VALUES ('系统参数配置新增', (SELECT max(id) from (SELECT * from sys_menu ) as temp where `name` = '系统参数配置'), 5, '', 'menuItem', 'F', '1', '0', 'common.config.save', '#', '1', now(), '', now(), '', 1, '0');
INSERT INTO sys_menu(`name`, `parent_id`, `order_num`, `url`, `target`, `menu_type`, `visible`, `is_refresh`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `version`, `del_flag`)VALUES ('系统参数配置详情', (SELECT max(id) from (SELECT * from sys_menu ) as temp where `name` = '系统参数配置'), 4, '', 'menuItem', 'F', '1', '0', 'common.config.info', '#', '1', now(), '', now(), '', 1, '0');
INSERT INTO sys_menu(`name`, `parent_id`, `order_num`, `url`, `target`, `menu_type`, `visible`, `is_refresh`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `version`, `del_flag`)VALUES ('系统参数配置修改', (SELECT max(id) from (SELECT * from sys_menu ) as temp where `name` = '系统参数配置'), 3, '', 'menuItem', 'F', '1', '0', 'common.config.update', '#', '1', now(), '', now(), '', 1, '0');
INSERT INTO sys_menu(`name`, `parent_id`, `order_num`, `url`, `target`, `menu_type`, `visible`, `is_refresh`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `version`, `del_flag`)VALUES ('系统参数配置删除', (SELECT max(id) from (SELECT * from sys_menu ) as temp where `name` = '系统参数配置'), 2, '', 'menuItem', 'F', '1', '0', 'common.config.delete', '#', '1', now(), '', now(), '', 1, '0');
INSERT INTO sys_menu(`name`, `parent_id`, `order_num`, `url`, `target`, `menu_type`, `visible`, `is_refresh`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `version`, `del_flag`)VALUES ('系统参数配置导出', (SELECT max(id) from (SELECT * from sys_menu ) as temp where `name` = '系统参数配置'), 1, '', 'menuItem', 'F', '1', '0', 'common.config.export', '#', '1', now(), '', now(), '', 1, '0');
