
-- 初始化菜单
INSERT INTO sys_menu(`name`, `parent_id`, `order_num`, `url`, `target`, `menu_type`, `visible`, `is_refresh`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `version`, `del_flag`)VALUES ('体重记录', 0, 0, 'manage/weigh/index', 'menuItem', 'C', '1', '0', 'manage.weigh.page', '#', '1', now(), '', now(), '', 1, '0');

INSERT INTO sys_menu(`name`, `parent_id`, `order_num`, `url`, `target`, `menu_type`, `visible`, `is_refresh`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `version`, `del_flag`)VALUES ('体重记录查看', (SELECT max(id) from (SELECT * from sys_menu ) as temp where `name` = '体重记录'), 6, '', 'menuItem', 'F', '1', '0', 'manage.weigh.page', '#', '1', now(), '', now(), '', 1, '0');
INSERT INTO sys_menu(`name`, `parent_id`, `order_num`, `url`, `target`, `menu_type`, `visible`, `is_refresh`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `version`, `del_flag`)VALUES ('体重记录新增', (SELECT max(id) from (SELECT * from sys_menu ) as temp where `name` = '体重记录'), 5, '', 'menuItem', 'F', '1', '0', 'manage.weigh.save', '#', '1', now(), '', now(), '', 1, '0');
INSERT INTO sys_menu(`name`, `parent_id`, `order_num`, `url`, `target`, `menu_type`, `visible`, `is_refresh`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `version`, `del_flag`)VALUES ('体重记录详情', (SELECT max(id) from (SELECT * from sys_menu ) as temp where `name` = '体重记录'), 4, '', 'menuItem', 'F', '1', '0', 'manage.weigh.info', '#', '1', now(), '', now(), '', 1, '0');
INSERT INTO sys_menu(`name`, `parent_id`, `order_num`, `url`, `target`, `menu_type`, `visible`, `is_refresh`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `version`, `del_flag`)VALUES ('体重记录修改', (SELECT max(id) from (SELECT * from sys_menu ) as temp where `name` = '体重记录'), 3, '', 'menuItem', 'F', '1', '0', 'manage.weigh.update', '#', '1', now(), '', now(), '', 1, '0');
INSERT INTO sys_menu(`name`, `parent_id`, `order_num`, `url`, `target`, `menu_type`, `visible`, `is_refresh`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `version`, `del_flag`)VALUES ('体重记录删除', (SELECT max(id) from (SELECT * from sys_menu ) as temp where `name` = '体重记录'), 2, '', 'menuItem', 'F', '1', '0', 'manage.weigh.delete', '#', '1', now(), '', now(), '', 1, '0');
INSERT INTO sys_menu(`name`, `parent_id`, `order_num`, `url`, `target`, `menu_type`, `visible`, `is_refresh`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `version`, `del_flag`)VALUES ('体重记录导出', (SELECT max(id) from (SELECT * from sys_menu ) as temp where `name` = '体重记录'), 1, '', 'menuItem', 'F', '1', '0', 'manage.weigh.export', '#', '1', now(), '', now(), '', 1, '0');
